### PR TITLE
Include extra extensions in glob for --all switch

### PR DESCRIPTION
**Pull request by lloydcotten**
This adds support to automatically include configured extensions when using the --all switch as per issue #174.

I simply modified an existing test to cover this scenario.

### CODE REVIEW

**Comment by bcoe** [comment]
@lloydcotten great catch/fix :+1:

my only comment, is that I think it would be worth adding an additional test. something like:

`outputs an empty coverage report for all supported extensions`

rather than tacking this logic onto the existing test.

**Comment by novemberborn** [comment]
Cool. +1 on making it a separate test.

**Comment by lloydcotten** [comment]
@bcoe @novemberborn I sat there and debated whether I should do that extra test or not.  I suppose I should know by now that if in doubt, I should just do a new test.  :-)

It's updated now.

**Comment by novemberborn** [comment]
:shipit:

**Comment by lloydcotten** [comment]
@bcoe Any idea why `master` branch is failing after the merge?  Seems to be failing on an unrelated test.

**Comment by lloydcotten** [comment]
Should mention that is on Travis - passes OK locally for me.

**Comment by bcoe** [comment]
@lloydcotten mind giving this branch a shot:

https://github.com/bcoe/nyc/pull/180

should fix the broken build on master ... not quite sure why that cropped up when it did.

**Comment by bcoe** [comment]
@lloydcotten give this a shot:

`npm i nyc@next`

shipped with your `--all` fixes. I'll release it to `latest` soon if everyone's testing goes well.

**Pull request merged**
