### PR TITLE
This adds --complete which will instrument all files in the project

### LINKED ISSUE #39: What about my untested files?
Hi,

So I tried out nyc on my project that I test with tape. I noticed that it doesn't report about files that are never touched by unit tests. Is this expected behavior? Everything looks very green, when in reality some files aren't yet tested at all.

### PR DESCRIPTION
**Pull request by ronkorving**
Fixes #39 

This is my attempt at solving the issue we discussed in #39. Please check thoroughly to see if I overlooked anything. No unit tests at this point, but I expect you will want some. It's Friday night now (Japan time) and I'm getting tired though, so I'm gonna leave it at this for now. Feedback welcome!

### CODE REVIEW

**Comment by bcoe** [comment]
@ronkorving elegant approach, I love it :+1: 

Did you get any feedback from the folks at Istanbul?

**Comment by ronkorving** [comment]
Unfortunately, none.

**Comment by ronkorving** [comment]
I noticed the test suite isn't all that big on nyc. Is this something you want to have covered? If not necessarily, could you please try it out, let me know if anything is missing, so I can fix it? I would love to see this land :)

**Comment by bcoe** [comment]
@ronkorving two steps ahead of me :) let's land this and try to potentially get this feature landed in Istanbul at a later date. @davglass mentioned he might be creating an istanbul org, which we could potentially move nyc into.

**Comment by ronkorving** [comment]
Sounds good! Let me if know if you need anything to be added or changed on this PR to get it ready for merging.

**Comment by bcoe** [comment]
made a few minor changes and added some tests, let me know what you think:

https://github.com/bcoe/nyc/pull/44

**Pull request closed without merging**
