### PR TITLE
Add some CLI testing

### PR DESCRIPTION
**Pull request by addaleax**
Add regression tests for #209 and #190. Feel very free to point out things you’d like to be changed! :smile: 
And btw, these tests should work on CI systems, but fail for me locally when I use the node/npm binaries that are *not* shipped with their tarballs (`make install` from the Node.js git source). tapjs/spawn-wrap#19 should address that, though.

### CODE REVIEW

**Comment by bcoe** [comment]
@addaleax awesome \o/ thanks for biting the bullet and starting to write some integration tests for the CLI. 

A few thoughts:

* let's pull the cli integration tests into their own test file, perhaps called `nyc-bin.js`.
* let's start displaying coverage information for `bin/nyc.js`.
* let's also pull the fixtures into their own sub-folder, probably called `cli`.

Really appreciate your contributions \o/

**Comment by addaleax** [comment]
> let's pull the cli integration tests into their own test file, perhaps called `nyc-bin.js`.

Sounds like a good idea. Two things:
1. This would require re-writing `build-tests.js` to handle both files, or make it take an argument indicating which source file to split up, right?
2. There are already some tests which spawn the `nyc` cli – Should these be moved, too?

**Comment by bcoe** [comment]
@addaleax correct me if I'm wrong, but I don't think the build step for `source-map-cache.js` is as complex as the `nyc-test.js` build process? I think we can probably copy the approach used for `source-map-cache.js`.

I would say: if the tests are specifically exercising aspects of the cli: how it parses arguments, its various commands, its exit codes; let's pull them into this new file.

The build step of the tests is designed to test the nitty-gritty functionality if `index.js` in a few different modes of operation, cached, uncached, etc.

**Comment by addaleax** [comment]
@bcoe No, you’re right, that’s why I’m asking :-) I’ll try that then, shouldn’t take too long.

**Comment by addaleax** [comment]
Btw, are you fine with the added symlinks? I don’t quite remember how current git implementations on Windows handle them (… is that why AppVeyor won’t start?)

**Comment by addaleax** [comment]
@bcoe Since all CI tests run on Node.js >= 0.12, is using `child_process.spawnSync` okay? That would definitely make the tests more concise.

**Comment by jamestalmage** [comment]
> I don't think the build step for source-map-cache.js is as complex as the nyc-test.js build process? I think we can probably copy the approach used for source-map-cache.js.

Correct. `nyc-test.js` is split into multiple files so you get a clean process for each test. This ended up being necessary because of the way `nyc` mucks with the currently running process (and because it doesn't behave well when you invoke it multiple times on the same process).

You probably still need a build step to create [`bin/nyc.covered`](https://github.com/addaleax/nyc/blob/cli-testing/test/src/nyc-test.js#L32) (same as how `source-map-cache.covered.js` is created). 

You should do something similar to [this](https://github.com/addaleax/nyc/blob/cli-testing/test/src/nyc-test.js#L32) to determine if the covered file exists or not.

---

@addaleax If the above stuff regarding coverage is confusing, feel free to just focus on writing some good tests and I can add coverage in another PR when you are done.

**Comment by addaleax** [comment]
@jamestalmage It’s not confusing by itself – like, I know the purpose and how it works in theory – but you obviously have the advantage of practical experience with the necessary steps. So, if you have the time, feel free to do that :+1:

**Comment by addaleax** [comment]
@bcoe The last commit adds the test cases I talked about… Travis should become green when including the spawn-wrap PR

**Comment by bcoe** [comment]
@addaleax looks like you might have already, but if you rebase these tests should now start passing.

**Comment by addaleax** [comment]
@bcoe yup, just did after you merged #226 :smile: but Travis is green here too, so that should be fine… is there anything else that should definitely go into this PR?

**Comment by bcoe** [comment]
@addaleax this rocks and you rock.

**Pull request merged**
