### PR TITLE
Babel/ES2015 Support

### PR DESCRIPTION
**Pull request by bcoe**
with the `--babel` flag, nyc is the easiest way to add ES2015 support to your project:

1. install the appropriate babel dependencies for your project (`npm i babel-core babel-preset-es2015 --save`).
2. create a `.babelrc` file:

```json
{
  "presets": ["es2015"]
}
```

3. install nyc, and run it with the `--babel` flag:

```sh
nyc --babel mocha
```

nyc uses source-maps to map coverage information back to the appropriate lines of the pre-transpiled code:

screen shot 2015-11-26 at 1 57 47 pm

This is a pretty big change, and I would love some help with the code review, you can try it out in your project by running:

```sh
npm i nyc@alpha --save-dev
```

I hope it solves the problems folks were having with nyc + babel:

CC: @Janpot, @shannonmoeller, @lfilho, @sindresorhus

### CODE REVIEW

**Comment by shannonmoeller** [comment]
Fantastic! Thanks!

**Comment by sindresorhus** [comment]
// @jamestalmage @vdemedes

**Comment by jamestalmage** [comment]
// @novemberborn

**Comment by shannonmoeller** [comment]
Couple things:

1. I had to add `babel-polyfill` to my `test.js` file. Is that expected?
2. NYC's version of Istanbul is out-of-date. I manually bumped it to 0.4.1 and it worked out-of-the-box.

**Comment by bcoe** [comment]
@shannonmoeller is babel-polyfill an alternative to using `.babelrc` with an appropriate preset? I think that this is how babel recommends doing things now?

Things worked well otherwise? You'd be happy to see this land?

**Comment by shannonmoeller** [comment]
Ah. It's because I'm [using async/await](http://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined-with-async-await) in my test file.

I'd absolutely love to see this land. Once `ava` supports Babel 6, I can switch from `blue-tape` and enter node testing nirvana.

Thanks for your work on this! :clap:

**Comment by bcoe** [comment]
@shannonmoeller do you think that `nyc` should make an attempt to require `babel-polyfill`? If this is a dependency in the package.json, is it a general rule that we will always want to include it?

**Comment by shannonmoeller** [comment]
As long as it's clearly documented as a feature of the `--babel` flag, I think that would be okay. Depends on how many assumptions you're comfortable making.

What about having a `require` config/flag similar to [`mocha`'s](https://mochajs.org/#r-require-lt-module-name-gt)?

```js
// package.json
{
  "config": {
    "nyc": {
      "require": ["babel-polyfill"]
    }
}
```

**Comment by bcoe** [comment]
@shannonmoeller I like this concept for the API much better than having a `--babel` flag \o/

see: https://github.com/bcoe/nyc/commit/1735bfdc819f60e4b4a30b87750174951c210207

And let me know if this does the trick for you:

`nyc --require babel-polyfill  --require babel-core/register`

**Comment by shannonmoeller** [comment]
Now that's beautiful. This is working perfectly for me:

```js
{
  "name": "foo",
  "version": "1.0.0",
  "main": "src/index.js",
  "scripts": {
    "coveralls": "nyc report -r text-lcov | coveralls",
    "test": "nyc -r html -r text blue-tape test/*.js",
    "watch": "watch 'npm run test' src test -d"
  },
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.2.1",
    "babel-polyfill": "^6.2.0",
    "babel-preset-es2015": "^6.1.18",
    "babel-preset-stage-0": "^6.1.18",
    "babel-register": "^6.2.0",
    "blue-tape": "^0.1.11",
    "coveralls": "^2.11.4",
    "nyc": "git+https://github.com/bcoe/nyc.git#1735bfdc",
    "watch": "^0.16.0"
  },
  "config": {
    "nyc": {
      "require": [
        "babel-register",
        "babel-polyfill"
      ]
    }
  }
}
```

**Comment by shannonmoeller** [comment]
I really like how this change makes this a bring-your-own-transpiler coverage tool. Works just as easily with coffeescript and typescript now.

**Comment by Janpot** [comment]
@bcoe Yes, this:

`nyc -r babel-core/register npm test` !

**Comment by jwhitfieldseed** [comment]
I get `SyntaxError: Unexpected token import` running `$ npm test` with `package.json`:

````json
{
  "scripts": {
    "test": "nyc tape \"./test/**/*.js\" | faucet",
  },
  "config": {
    "nyc": {
      "require": [
        "babel-register",
        "babel-polyfill"
      ]
    }
  },
  "devDependencies": {
    "babel-cli": "^6.2.0",
    "babel-core": "^6.2.1",
    "babel-preset-es2015": "^6.1.18",
    "faucet": "0.0.1",
    "istanbul": "^0.3.17",
    "lodash": "^3.10.0",
    "nyc": "git+ssh://git@github.com:bcoe/nyc.git#babel",
    "pegjs": "^0.8.0",
    "sql.js": "^0.2.21",
    "tape": "^4.0.1"
  }
}

````

`babel-runtime` seems to be required because I need `regeneratorRuntime`.

With this setup, however, `$ npm run coverage` works as expected.

````json
"scripts": {
    "test": "babel-node $( which tape) \"./test/**/*.js\" | faucet",
    "coverage": "nyc npm test --reporter lcov",
  }
````

Can you see what I'm doing wrong in my first example?

**Comment by bcoe** [comment]
@jwhitfieldseed is the code your instrumenting open-source, mind linking me to the project and I'll take a look?

@Janpot did you give that a shot with a couple of your projects? I'd like to publish this pretty soon :+1:

**Comment by jwhitfieldseed** [comment]
@bcoe nvm, `rm -rf node_modules && npm i` did the trick :smile:

**Comment by jwhitfieldseed** [comment]
@bcoe actually, scratch that. This setup works with node@5.1.0, fails with node@4.1.1:

https://github.com/jwhitfieldseed/prequel/blob/master/package.json
https://travis-ci.org/jwhitfieldseed/prequel

Error with node 4.1.1:

````
(function (exports, require, module, __filename, __dirname) { import test from "tape";
                                                              ^^^^^^
SyntaxError: Unexpected reserved word
...
````

**Comment by shannonmoeller** [comment]
@jwhitefieldseed Looks like you need to `npm i -D babel-require babel-polyfill`

**Comment by jwhitfieldseed** [comment]
@shannonmoeller That didn't fix it, I'm afraid. 

At first thought it was a problem with my Babel 6 config rather than `nyc` interop, but, on Node 4, this `npm test` script works:

    "test": babel-node $(which tape) \"./test/**/*.js\" | faucet"

And this fails:

    "test": "nyc tape \"./test/**/*.js\" | faucet && nyc report --reporter text",

Both work on Node 5.

**Comment by jwhitfieldseed** [comment]
@shannonmoeller Ah - `babel-register`, not `babel-require`. Should have realised that! Problem solved, sorry about the noise. nyc with Babel is looking excellent :+1:

**Comment by shannonmoeller** [comment]
Yep! Sorry about the typo.

**Comment by bcoe** [comment]
@shannonmoeller @jwhitfieldseed, given that you now explicitly specify a list of libraries to require, perhaps I should stop using `try-require` and let it simply throw? I think this would have helped bring out this typo sooner?

**Comment by shannonmoeller** [comment]
@bcoe Sounds good to me.

**Comment by jwhitfieldseed** [comment]
@bcoe :+1:  I would have caught the difference between Node 4 and Node 5 (or as I now realise, npm 2 vs npm 3) immediately with an early `Cannot find module 'babel-register'`.

**Comment by bcoe** [comment]
@mindmelting just published a hot-fix of `nyc`, `nyc@4.0.1` which should solve this problem for you.

Let me know if it does the trick?

**Pull request merged**
