### PR TITLE
fix: upgrade foreground-child dependency

### PR DESCRIPTION
**Pull request by bcoe**
@addaleax @jamestalmage mind giving this a spin while builds run?

### CODE REVIEW

**Comment by jamestalmage** [comment]
`spawn-wrap` is still on `foreground-child@1.3`

**Comment by addaleax** [comment]
Looks good locally and I think bundling an npm3-style tree should take care of the old version that `spawn-wrap` depends on, right?

**Comment by bcoe** [comment]
@jamestalmage @addaleax my plan is to bundle on a npm@2.x tree, which solves some singleton issues with our dependencies -- but! I think we should be fine as long as I re-install everything prior to publish? `spawn-wrap` isn't itself bundled or pinned.

**Comment by addaleax** [comment]
I guess that should work. If the copy of `foreground-child` in `spawn-wrap`’s dependencies is still outdated after that for some reason, you can probably also just remove it and let `spawn-wrap` use the top-level one.

**Comment by jamestalmage** [comment]
Yeah - actually, it's a carrot dependency, so it should be deduped. 

Why does bundling on `npm@2` solve problems?

**Comment by bcoe** [comment]
@jamestalmage nyc relies on a few popular dependencies that themselves use a singleton pattern (for various reasons, maintaining state, etc).

Bundling dependencies helped to solve this issue, but I found that deduping dependencies and publishing with npm@3.x continued to introduce some regressions:

https://github.com/bcoe/nyc/issues/246

**Comment by jamestalmage** [comment]
Hmm.

Have we figured out **why** that is happening? Is there a bug somewhere in `npm`? Ideally we wouldn't be so brittle.

**Pull request merged**
