### PR TITLE
Removed yargs default for reporters so the ones defined in  are taken first

### PR DESCRIPTION
**Pull request by rapzo**
As pointed in [issue #184](https://github.com/bcoe/nyc/issues/184).

### CODE REVIEW

**Comment by bcoe** [comment]
wouldn't this approach make it so that it's impossible to override the reporter:

`nyc --reporter=lcov-text`

the goal is a solution that uses the reporter defined in `package.json` `iff` the default reporter has been set by yargs?

**Comment by rapzo** [comment]
Yeah, you're right...
Well, i thought the expected behaviour was to run through the list of reporters defined in `package.json` when no reporter was provided by yargs. Shouldn't it be?

**Comment by rapzo** [comment]
Went a bit up and removed the yargs' default for reporters since it is set [here](https://github.com/bcoe/nyc/blob/master/index.js#L36) when none provided. Seems to work both ways.

**Comment by bcoe** [comment]
@rapzo I dug into this a bit more, there's a slightly better solution that allows us to continue having a default value:

```js
  .option('reporter', {
    alias: 'r',
    describe: 'coverage reporter(s) to use',
    global: true
  })
```

there appears to be a bug with yargs, which is taking into account aliases when loading defaults from the `nyc` stanza in the package.json. A temporary fix is to edit `bin/nyc.js` so that the long option name is used for the option rather than the alias.

I'd happily land this patch, but we should also dig into this bug in yargs.

**Comment by rapzo** [comment]
Sorry for the delay. Here's the patch. A better solution indeed.

**Comment by bcoe** [comment]
@rapzo give this a shot, shipped with your fixes for package configuration:

`npm i nyc@next`

If everything is looking good I'll promote the change to `latest` soon.

**Comment by rapzo** [comment]
I will! Thanks man!

**Pull request merged**
